INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de dos ruedas hasta cincuenta centimetros cubicos (50 c.c.) de cilindrada');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de dos ruedas de mas de cincuenta centimetros cubicos (50 c.c.) y hasta ciento cincuenta centimetros cubicos (150 c.c.) de cilindrada');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de dos ruedas de mas de ciento cincuenta centimetros cubicos (150 c.c.) y hasta trescientos centimetros cubicos (300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitacion por dos (2) años en la clase A.2.1.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de dos ruedas de mas de trescientos centimetros cubicos (300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitacion por dos (2) años en clase A.2.2');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de tres o cuatro ruedas hasta cincuenta centimetros cubicos ( 50 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de tres o cuatro ruedas de mas de cincuenta centimetros cubicos (50 c.c.) y hasta ciento cincuenta centimetros cubicos ( 150 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de tres o cuatro ruedas de mas de ciento cincuenta centimetros cubicos ( 150 c.c.) y hasta trescientos centimetros cubicos ( 300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitacion por dos años en la clase A.4.2');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehiculos de tres o cuatro ruedas de mas de trescientos centimetros cubicos (300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitacion por dos (2) años en la Clase A.4.3');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de dos ruedas hasta cincuenta centimetros cubicos (50 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de dos ruedas de mas de cincuenta centimetros cubicos (50 c.c.) y hasta ciento cincuenta centimetros cubicos (150 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de dos ruedas de mas de ciento cincuenta centimetros cubicos (150 c.c.) y hasta trescientos centimetros cubicos (300 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de dos ruedas de mas de trescientos centimetros cubicos (300 c.c.) de cilindrada');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de tres o cuatro ruedas de hasta cincuenta centimetros cubicos (50 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de tres o cuatro ruedas de mas de cincuenta centimetros cubicos (50 c.c.) y hasta ciento cincuenta centimetros cubicos (150 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de tres o cuatro ruedas de mas de ciento cincuenta centimetros cubicos (150 c.c.) y hasta trescientos centimetros cubicos (300 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehiculos de tres o cuatro ruedas de mas de trescientos centimetros cubicos (300 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Automoviles, camionetas y utilitarios hasta tres mil quinientos kilogramos (3.500 kg.) de peso.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Automoviles, camionetas y utilitarios hasta tres mil quinientos kilogramos (3.500 kg.) de peso, con un acoplado de hasta setecientos cincuenta kilogramos (750 kg.) de peso, o casa rodante no motorizada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Camion sin acoplado ni semiacoplado y casas rodantes motorizadas de mas de tres mil quinientos kilogramos (3.500 kg.) de peso. Incluye B.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehiculos de transporte hasta 4 pasajeros, excluido el conductor. Incluye Clase B.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehiculos de transporte de 5 y hasta 20 pasajeros, excluido el conductor. Incluye clases B.1 y D.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehiculos de transporte de mas de 20 pasajeros, excluido el conductor. Incluye Clases B.1, D.1 y D.2.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Camiones articulados, con acoplado o semiacoplado. Incluye Clases B y C');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Maquinaria especial no agricola.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehiculos correspondientes a las diversas Clases, segun el caso. La licencia consignara la descripcion de la adaptacion que corresponda a la discapacidad de su titular.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Tractores Agricolas.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Maquinaria Especial Agricola.');
