INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ASEG. DE CAUCIONES');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ASEG.CRED. Y GTIAS.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA HOLANDO');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA MERIDIONAL');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('PARANA S.A. DE SEG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('HSBC-LA BUENOS AIRES');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ZURICH ARGENTINA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('BOSTON');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA REPUBLICA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('AXA SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('XL INSURANCE ARG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('BERKLEY INTERNACIONA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA EQUITATIVA PLATA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('PROVINCIA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA CONSTRUCCION');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('FED.PAT.SEGUROS SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA PATAGONIA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ROYAL & SUN ALLIANCS');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA TERRITORIAL');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CIA. SEG.EUROAMERICA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA SEGUNDA COOP-');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('PRUDENCIA CIA.ARG.SG');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('JUNCAL SEG.AUT.Y PAT');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LIDERAR');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('TRIUNFO COOPERATIVO');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CALEDONIA ARGENTINA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA MERCANTIL ANDINA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('INST.DE SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('SAN CRISTOBAL');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ARGOS');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ANTARTIDA CIA.ARG.SE');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('SANCOR COOPERATIVA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('RIO URUGUAY');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('FIANZAS Y CREDITO SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('BBVA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('BERNARDINO RIVADAVIA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LUA SEG. LA PORTENA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ALBA CIA. ARG.SEG SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('METROPOL');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('EL COMERCIO');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('INSTITUTO');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('EL SURCO');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CHUBB DE FIANZAS');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CIA. SEG. LATITUD SU');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('MAPFRE ARG. SEG. SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('COOPER.LUZ Y FUERZA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('PROD. FRUTAS ARGENT.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('COSENA SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ALLIANZ ARGENTINA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CAJA DE SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA ECONOMIA COM.S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('SMG CIA.ARG. DE SEG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('LA PERSEVERANCIA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('FATA SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ESCUDO SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CIA.ARG.SEG.VICTORIA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('GENERALI ARGENTINA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CHUBB ARG, DE SEG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('TPC CÍA. DE SEG. SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('TRAINMET SEGUROS S.A');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('COFACE');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('NIVEL SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('AFIANZADORA LATIN.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('INTEGRITY SEG.ARG SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('COOPERACION MUTUAL');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('NOBLE S.A.ASEG.RESP.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('SEGURCOOP COOP.SEG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CESCE ARG. S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('INST.ASEG.MERCANTIL');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('NACION SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ACE SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CIA.DE SEG.INSUR S.A');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('ASSEKURANSA CÍA.SEG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('TESTIMONIO CIA. SEG.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('BENEFICIO SA CIA.SEG');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CIA.DE SEG.EL NORTE');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('CREDITO Y CAUCION SA');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('TUTELAR SEGUROS S.A.');
INSERT INTO CompaniaDeSeguros			(NombreCompania) 												VALUES ('GALICIA SEGUROS S.A.');
