INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Hurto');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Robo');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Extorsion');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Estafa');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Apropiacion indebida');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Daños');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Presentacion de datos confiables falsos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Trafico de droga');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conduccion con velocidad excesiva');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conduccion bajo influencia de toxicos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conduccion temeraria');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conduccion con manifiesto desprecio por la vida de los demas');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Falsificacion de moneda');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Calumnia');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Injuria');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('malversacion de caudales publicos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('malversacion de caudales publicos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('trafico de influencias');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('cohecho');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('revelacion de secretos o informaciones por autoridad o funcionario publico');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('acceso a documentos secretos y de destruccion o inutilizacion de sus medios de acceso');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('infidelidad en la custodia de documentos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('desobediencia y denegacion de auxilio');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('abandono de un servicio publico');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('abandono de destino y omision del deber de perseguir delitos');
