INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Adelantar o sobrepasar en forma indebida a otro vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No hacer señales, ni tomar las precauciones para girar, voltear en U, pasar de un carril de la calzada a otro o detener el vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Detener el vehiculo bruscamente sin motivo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No detenerse antes de la linea de parada o antes de las areas de interseccion de calzadas o no respetar el derecho de paso del peaton.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No mantener una distancia suficiente, razonable y prudente, de acuerdo al tipo de vehiculo y la via por la que se conduce, mientras se desplaza o al detenerse detras de otro.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No ubicar el vehiculo con la debida anticipacion en el carril donde va efectuar el giro o volteo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No conducir por el carril de extremo derecho de la calzada un vehiculo del servicio de transporte publico de pasajeros o de carga o de desplazamiento lento o un vehiculo automotor menor.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No utilizar el carril derecho para recoger o dejar pasajeros o carga.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Retroceder, salvo casos indispensables para mantener libre la circulacion, para incorporarse a ella o para estacionar el vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Incumplir las disposiciones sobre el uso de las vias de transito rapido y/o de acceso restringido.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular, estacionar o detenerse sobre una isla de encauzamiento, canalizadora, de refugio o divisoria del transito, marcas delimitadoras de carriles, separadores centrales, bermas, aceras, areas verdes, pasos peatonales, jardines o rampas para minusvalidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Girar estando el semaforo con luz roja y flecha verde, sin respetar el derecho preferente de paso de los peatones.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo con mayor numero de personas al numero de asientos señalado en la Tarjeta de Identificacion Vehicular, con excepcion de niños en brazos en los asientos posteriores; y, llevar pasajeros de pie en vehiculos del servicio publico de transporte urbano de pasajeros si la altura interior del vehiculo es menor a 1.80 metros.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Tener la puerta, capot o maletera del vehiculo abierta, cuando el vehiculo esta en marcha.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No utilizar las luces intermitentes de emergencia de un vehiculo cuando se detiene por razones de fuerza mayor, obstaculizando el transito, o no colocar los dispositivos de seguridad reglamentarios cuando el vehiculo queda inmovilizado en la via publica.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo por una via en la cual no esta permitida la circulacion o sobre mangueras contra incendio.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehiculos que tengan lunas o vidrios polarizados o acondicionados de modo tal que impidan la visibilidad del interior del vehiculo, sin la autorizacion correspondiente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo haciendo uso de telefono celular, radio portatil o similar o cualquier otro objeto que impida tener ambas manos sobre el volante de direccion.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo de la categoria M o N que carezca de vidrios de seguridad reglamentarios o que su parabrisas se encuentre deteriorado, trizado o con objetos impresos, calcomanias, carteles u otros elementos en el area de barrido del limpiaparabrisas y que impidan la visibilidad del conductor o un vehiculo de la categoria L5 que contando con parabrisas, micas o similares, tengan objetos impresos, calcomanias, carteles u otros elementos que impidan la visibilidad del conductor. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo que no cuenta con las luces y dispositivos retrorreflectivos previstos en los reglamentos pertinentes.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo sin espejos retrovisores.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo cuando llueve, llovizne o garue, sin tener operativo el sistema de limpiaparabrisas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo del servicio de transporte publico urbano de pasajeros con personas de pie, si la altura interior del vehiculo no supera a 1,80 metros.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo con el motor en punto neutro o apagado.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo sin portar el certificado del Seguro Obligatorio de Accidentes de Transito o Certificado Contra Accidentes de Transito, o que estos no correspondan al uso del vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo de la categoria M o N con la salida del tubo de escape en la parte lateral derecha, de modo tal que las emisiones o gases sean expulsados hacia la acera por donde circulan los peatones.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo cuya carga o pasajeros obstruya la visibilidad de los espejos laterales.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('En vehiculos de las categorias M y N, no llevar puesto el cinturon de seguridad y/o permitir que los ocupantes del vehiculo no lo utilicen en los casos en que, de acuerdo a las normas vigentes, exista tal obligacion. En vehiculos automotores de la categoria L5 no contar con cinturones de seguridad para los asientos de los pasajeros o no tener uno o mas soportes fijados a su estructura que permitan a los pasajeros asirse de ellos mientras son transportados.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular en forma desordenada o haciendo maniobras peligrosas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular transportando personas en la parte exterior de la carroceria o permitir que sobresalga parte del cuerpo de la(s) persona(s) transportada(s) en el vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('En las vias publicas urbanas, circular en la noche o cuando la luz natural sea insuficiente o cuando las condiciones de visibilidad sean escasas, sin tener encendido el sistema de luces reglamentarias; o en la red vial nacional y departamental o regional, circular sin tener las luces bajas encendidas durante las veinticuatro (24) horas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular por vias o pistas exclusivas para bicicletas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular transportando cargas que sobrepasen las dimensiones de la carroceria o que se encuentren ubicadas fuera de la misma; o transportar materiales sueltos, fluidos u otros sin adoptar las medidas de seguridad que impidan su caida a la via.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Remolcar vehiculos sin las medidas de seguridad.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Usar luces altas en vias urbanas o hacer mal uso de las luces.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Compartir el asiento de conducir con otra persona, animal o cosa.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No reducir la velocidad al ingresar a un tunel o cruzar un puente, intersecciones o calles congestionadas, cuando transite por cuestas, cuando se aproxime y tome una curva o cambie de direccion, cuando circule por una via estrecha o sinuosa, cuando se encuentre con un vehiculo que circula en sentido contrario o cuando existan peligros especiales con respecto a los peatones u otros vehiculos o por razones del clima o condiciones especiales de la via.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Transitar lentamente por el carril de la izquierda, causando congestion o riesgo o rapidamente por el carril de la derecha.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Aumentar la velocidad cuando es alcanzado por otro vehiculo que tiene la intencion de sobrepasarlo o adelantarlo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar el vehiculo en zonas prohibidas o rigidas señalizadas o sin las señales de seguridad reglamentarias en caso de emergencia. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar o detener el vehiculo sobre la linea demarcatoria de interseccion, dentro de estas o en el crucero peatonal (paso peatonal).');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar frente a la entrada o salida de garajes, estacionamientos publicos, vias privadas o en las salidas de salas, espectaculos, centros deportivos en funcionamiento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar a una distancia menor de cinco (5) metros de una bocacalle, de las entradas de hospitales o centros de asistencia medica, cuerpos de bomberos o de hidrantes de servicio contra incendios, salvo los vehiculos relacionados a la funcion del local.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar a menos de tres (3) metros de las puertas de establecimientos educacionales, teatros, iglesias y hoteles, salvo los vehiculos relacionados a la funcion del local.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar a menos de veinte (20) metros de un cruce ferroviario a nivel.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en zonas no permitidas por la autoridad competente, a menos de diez (10) metros de un cruce peatonal o de un paradero de buses, asi como en el propio sitio determinado para la parada del bus.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en lugar que afecte la operatividad del servicio de transporte publico de pasajeros o carga o que afecte la seguridad, visibilidad o fluidez del transito o impida observar la señalizacion.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un omnibus, microbus, casa rodante, camion, remolque, semirremolque, plataforma, tanque, tractocamion, trailer, volquete o furgon, en en vias publicas de zona urbana, excepto en los lugares que habilite para tal fin la autoridad competente, mediante la señalizacion pertinente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehiculo de categorìa M, N u O a una distancia menor a un metro de la parte delantera o posterior de otro ya estacionado, salvo cuando se estacione en diagonal o perpendicular a la via.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en los terminales o estaciones de ruta, fuera de los estacionamientos externos determinados por la Autoridad competente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehiculo automotor por la noche en lugares donde, por la falta de alumbrado publico, se impide su visibilidad, o en el dia, cuando, por lluvia, llovizna o neblina u otro factor, la visibilidad es escasa, sin mantener encendidas las luces de estacionamiento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehiculo en vias con pendientes pronunciadas sin asegurar su inmovilizacion.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Desplazar o empujar un vehiculo bien estacionado, con el proposito de ampliar un espacio o tratar de estacionar otro vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Abandonar el vehiculo en la via publica.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar la via publica para efectuar reparaciones, salvo casos de emergencia.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Recoger o dejar pasajeros fuera de los paraderos de ruta autorizados, cuando existan.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No respetar las señales que rigen el transito, cuyo incumplimiento no se encuentre tipificado en otra infraccion. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No presentar la Tarjeta de Identificacion Vehicular, la Licencia de Conducir o el Documento Nacional de Identidad o documento de identidad, segun corresponda. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo de categoria L, con excepcion de la categoria L5, sin tener puesto el casco de seguridad o anteojos protectores, en caso de no tener parabrisas; o permitir que los demas ocupantes no tengan puesto el casco de seguridad. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular con placas ilegibles o sin iluminacion o que tengan adherido algun material, que impida su lectura a traves de medios electronicos, computarizados u otro tipo de mecanismos tecnologicos que permitan verificar la comision de las infracciones de transito. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No llevar las placas de rodaje en el lugar que corresponde.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Incumplir con devolver las placas de exhibicion, rotativa o transitoria dentro de los plazos establecidos en el Reglamento de Placa unica Nacional de Rodaje. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar señales audibles o visibles iguales o similares a las que utilizan los vehiculos de emergencia o vehiculos oficiales.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo cuyas caracteristicas registrables o condiciones tecnicas han sido modificadas, alteradas o agregadas, atentando contra la seguridad de los usuarios o por no corresponder los datos consignados en la Tarjeta de Identificacion Vehicular con los del vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No ceder el paso a otros vehiculos que tienen preferencia.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Seguir a los vehiculos de emergencia y vehiculos oficiales para avanzar mas rapidamente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Detener el vehiculo sobre la demarcacion en el pavimento de la señal "No bloquear cruce"');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Dejar mal estacionado el vehiculo en lugares permitidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehiculo en zonas de parqueo destinadas a vehiculos que transportan a personas con discapacidad o conducidos por estos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar el Permiso Especial de Parqueo para Personas con Discapacidad por parte de una persona a la cual no le corresponde.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Abrir o dejar abierta la puerta de un vehiculo estacionado, dificultando la circulacion vehicular.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar el carril de giro a la izquierda para continuar la marcha en cualquier direccion que no sea la especificamente señalada.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Arrojar, depositar o abandonar objetos o sustancias en la via publica que dificulten la circulacion.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar la bocina para llamar la atencion en forma inncesaria.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Hacer uso de bocinas de descarga de aire comprimido en el ambito urbano.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir con presencia de alcohol en la sangre en proporcion mayor a lo previsto en el Codigo Penal, o bajo los efectos de estupefacientes, narcoticos y/o alucinogenos comprobado con el examen respectivo o por negarse al mismo y que haya participado en un accidente de transito.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir con presencia de alcohol en la sangre en proporcion mayor a lo previsto en el Codigo Penal, bajo los efectos de estupefacientes, narcoticos y/o alucinogenos comprobada con el examen respectivo o por negarse al mismo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo automotor sin tener licencia de conducir o permiso provisional.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehiculos estando la licencia de conducir retenida, suspendida o estando inhabilitado para obtener licencia de conducir.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo con Licencia de Conducir cuya clase o categoria no corresponde al vehiculo que conduce.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en las curvas, puentes, tuneles, zonas estrechas de la via, pasos a nivel, pasos a desnivel en cambios de rasante, pendientes y cruces de ferrocarril.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Participar en competencias de velocidad en eventos no autorizados.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Permitir a un menor de edad la conduccion de un vehiculo automotor, sin autorizacion o permiso provisional.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo con cualquiera de sus sistemas de direccion, frenos, suspension, luces o electrico en mal estado, previa inspeccion tecnica vehicular.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Abastecer de combustible un vehiculo del servicio de transporte publico de pasajeros con personas a bordo del vehiculo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehiculos de las categorias M o N sin parachoques o dispositivo antiempotramiento cuando corresponda; o un vehiculo de la categoria L5 sin parachoques posterior, conforme a lo establecido en el Reglamento Nacional de Vehiculos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No detenerse al aproximarse a un vehiculo de transporte escolar debidamente identificado que esta recogiendo o dejando escolares.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No detenerse al llegar a un cruce ferroviario a nivel o reiniciar la marcha sin haber comprobado que no se aproxima tren o vehiculo ferroviario, o cruzar la via ferrea por lugares distintos a los cruces a nivel establecidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular produciendo contaminacion en un indice superior a los limites maximos permisibles de emision de gases contaminantes.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular en sentido contrario al transito autorizado.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Cruzar una interseccion o girar, estando el semaforo con luz roja y no existiendo la indicacion en contrario.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Desobedecer las indicaciones del efectivo de la Policia Nacional del Peru asignado al control del transito.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehiculos sin cumplir con las restricciones que consigna la Licencia de Conducir.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No respetar los limites maximo o minimo de velocidad establecidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar interrumpiendo totalmente el transito.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Detenerse para cargar o descargar mercancias en la calzada y/o en los lugares que puedan constituir un peligro u obstaculo o interrumpan la circulacion.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar o detener el vehiculo en el carril de circulacion, en carreteras o caminos donde existe berma lateral.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular sin placas de rodaje o sin el permiso correspondiente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No dar preferencia de paso a los vehiuclos de emergencia y vehiculos oficiales cuando hagan uso de sus señales audibles y visibles.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo especial que no se ajuste a las exigencias reglamentarias sin la autorizacion correspondiente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo que no cuente con el certificado de aprobacion de inspeccion tecnica vehicular.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo sin contar con la poliza del Seguro Obligatorio de Accidentes de Transito, o Certificado de Accidentes de Transito, cuando corresponda, o estos no se encuentre vigente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Deteriorar intencionalmente, adulterar, destruir o sustraer las Placas de exhibicion, rotativa o transitoria . ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Usar las placas de exhibicion, rotativa o transitoria fuera del plazo, horario o ruta establecida o cuando esta ha caducado o ha sido invalidada. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar las placas de exhibicion, rotativa o transitoria en vehiculos a los que no se encuentren asignadas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Tramitar u obtener duplicado, recategorizacion, revalidacion, canje o nueva licencia de conducir de cualquier clase, por el infractor cuya licencia de conducir se encuentre retenida, suspendida o cancelada o se encuentre inhabilitado para obtenerla.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Operar maquinaria especial por la via publica.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular produciendo ruidos que superen los limites maximos permisibles.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Voltear en U sobre la misma calzada, en las curvas, puentes, pasos a desnivel, vias expresas, tuneles, estructuras elevadas, cima de cuesta, cruce ferroviario a nivel.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Transportar carga sin los dispositivos de sujecion o seguridad establecidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir y ocasionar un accidente de transito con daños personales inobservando las normas de transito dispuestas en el presente Reglamento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehiculo para el servicio de transporte publico y ocasionar un accidente de transito con daños personales inobservando las normas de transito dispuestas por el presente Reglamento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir y ocasionar un accidente de transito con lesiones graves o muerte inobservando las normas de transito dispuestas en el presente Reglamento.');
