INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (100, 'Ruta nacional Nro 1', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (200, 'Ruta nacional Nro 2', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (300, 'Ruta nacional Nro 3', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (400, 'Ruta nacional Nro 4', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (500, 'Ruta nacional Nro 5', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (600, 'Ruta nacional Nro 6', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (700, 'Ruta nacional Nro 7', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (800, 'Ruta nacional Nro 8', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (900, 'Ruta nacional Nro 9', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1000, 'Ruta nacional Nro 10', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1100, 'Ruta nacional Nro 11', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1200, 'Ruta nacional Nro 12', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1300, 'Ruta nacional Nro 13', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1400, '', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1500, '', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1600, '', 1);
INSERT INTO Camino 	(Longitud, Nombre, idTipoCamino) VALUES (1700, '', 1);
