INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de dos ruedas hasta cincuenta centímetros cúbicos (50 c.c.) de cilindrada');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de dos ruedas de más de cincuenta centímetros cúbicos (50 c.c.) y hasta ciento cincuenta centímetros cúbicos (150 c.c.) de cilindrada');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de dos ruedas de más de ciento cincuenta centímetros cúbicos (150 c.c.) y hasta trescientos centímetros cúbicos (300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitación por dos (2) años en la clase A.2.1.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de dos ruedas de más de trescientos centímetros cúbicos (300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitación por dos (2) años en clase A.2.2');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de tres o cuatro ruedas hasta cincuenta centímetros cúbicos ( 50 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de tres o cuatro ruedas de más de cincuenta centímetros cúbicos (50 c.c.) y hasta ciento cincuenta centímetros cúbicos ( 150 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de tres o cuatro ruedas de más de ciento cincuenta centímetros cúbicos ( 150 c.c.) y hasta trescientos centímetros cúbicos ( 300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitación por dos años en la clase A.4.2');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Motovehículos de tres o cuatro ruedas de más de trescientos centímetros cúbicos (300 c.c.) de cilindrada. Los menores de 21 años deben acreditar haber tenido habilitación por dos (2) años en la Clase A.4.3');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de dos ruedas hasta cincuenta centímetros cúbicos (50 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de dos ruedas de más de cincuenta centímetros cúbicos (50 c.c.) y hasta ciento cincuenta centímetros cúbicos (150 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de dos ruedas de más de ciento cincuenta centímetros cúbicos (150 c.c.) y hasta trescientos centímetros cúbicos (300 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de dos ruedas de más de trescientos centímetros cúbicos (300 c.c.) de cilindrada');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de tres o cuatro ruedas de hasta cincuenta centímetros cúbicos (50 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de tres o cuatro ruedas de más de cincuenta centímetros cúbicos (50 c.c.) y hasta ciento cincuenta centímetros cúbicos (150 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de tres o cuatro ruedas de más de ciento cincuenta centímetros cúbicos (150 c.c.) y hasta trescientos centímetros cúbicos (300 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Clase profesional para motovehículos de tres o cuatro ruedas de más de trescientos centímetros cúbicos (300 c.c.) de cilindrada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Automóviles, camionetas y utilitarios hasta tres mil quinientos kilogramos (3.500 kg.) de peso.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Automóviles, camionetas y utilitarios hasta tres mil quinientos kilogramos (3.500 kg.) de peso, con un acoplado de hasta setecientos cincuenta kilogramos (750 kg.) de peso, o casa rodante no motorizada.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Camión sin acoplado ni semiacoplado y casas rodantes motorizadas de más de tres mil quinientos kilogramos (3.500 kg.) de peso. Incluye B.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehículos de transporte hasta 4 pasajeros, excluido el conductor. Incluye Clase B.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehículos de transporte de 5 y hasta 20 pasajeros, excluido el conductor. Incluye clases B.1 y D.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehículos de transporte de más de 20 pasajeros, excluido el conductor. Incluye Clases B.1, D.1 y D.2.1');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Camiones articulados, con acoplado o semiacoplado. Incluye Clases B y C');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Maquinaria especial no agrícola.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Vehículos correspondientes a las diversas Clases, según el caso. La licencia consignará la descripción de la adaptación que corresponda a la discapacidad de su titular.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Tractores Agricolas.');
INSERT INTO CategoriaDeLicencia	(Nombre) VALUES ('Maquinaria Especial Agricola.');
