INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Hurto');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Robo');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Extorsión');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Estafa');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Apropiación indebida');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Daños');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Presentación de datos confiables falsos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Tráfico de droga');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conducción con velocidad excesiva');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conducción bajo influencia de tóxicos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conducción temeraria');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Conducción con manifiesto desprecio por la vida de los demás');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Falsificación de moneda');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Calumnia');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('Injuria');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('malversación de caudales públicos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('malversación de caudales públicos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('tráfico de influencias');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('cohecho');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('revelación de secretos o informaciones por autoridad o funcionario público');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('acceso a documentos secretos y de destrucción o inutilización de sus medios de acceso');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('infidelidad en la custodia de documentos');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('desobediencia y denegación de auxilio');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('abandono de un servicio público');
INSERT INTO TipoDeAntecedente (Nombre) VALUES ('abandono de destino y omisión del deber de perseguir delitos');
