INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Adelantar o sobrepasar en forma indebida a otro vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No hacer señales, ni tomar las precauciones para girar, voltear en U, pasar de un carril de la calzada a otro o detener el vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Detener el vehículo bruscamente sin motivo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No detenerse antes de la línea de parada o antes de las áreas de intersección de calzadas o no respetar el derecho de paso del peatón.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No mantener una distancia suficiente, razonable y prudente, de acuerdo al tipo de vehículo y la vía por la que se conduce, mientras se desplaza o al detenerse detrás de otro.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No ubicar el vehículo con la debida anticipación en el carril donde va efectuar el giro o volteo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No conducir por el carril de extremo derecho de la calzada un vehículo del servicio de transporte público de pasajeros o de carga o de desplazamiento lento o un vehículo automotor menor.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No utilizar el carril derecho para recoger o dejar pasajeros o carga.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Retroceder, salvo casos indispensables para mantener libre la circulación, para incorporarse a ella o para estacionar el vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Incumplir las disposiciones sobre el uso de las vías de tránsito rápido y/o de acceso restringido.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular, estacionar o detenerse sobre una isla de encauzamiento, canalizadora, de refugio o divisoria del tránsito, marcas delimitadoras de carriles, separadores centrales, bermas, aceras, áreas verdes, pasos peatonales, jardines o rampas para minusválidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Girar estando el semáforo con luz roja y flecha verde, sin respetar el derecho preferente de paso de los peatones.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo con mayor número de personas al número de asientos señalado en la Tarjeta de Identificación Vehicular, con excepción de niños en brazos en los asientos posteriores; y, llevar pasajeros de pie en vehículos del servicio público de transporte urbano de pasajeros si la altura interior del vehículo es menor a 1.80 metros.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Tener la puerta, capot o maletera del vehículo abierta, cuando el vehículo está en marcha.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No utilizar las luces intermitentes de emergencia de un vehículo cuando se detiene por razones de fuerza mayor, obstaculizando el tránsito, o no colocar los dispositivos de seguridad reglamentarios cuando el vehículo queda inmovilizado en la vía pública.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo por una vía en la cual no está permitida la circulación o sobre mangueras contra incendio.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehículos que tengan lunas o vidrios polarizados o acondicionados de modo tal que impidan la visibilidad del interior del vehículo, sin la autorización correspondiente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo haciendo uso de teléfono celular, radio portátil o similar o cualquier otro objeto que impida tener ambas manos sobre el volante de dirección.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo de la categoría M o N que carezca de vidrios de seguridad reglamentarios o que su parabrisas se encuentre deteriorado, trizado o con objetos impresos, calcomanías, carteles u otros elementos en el área de barrido del limpiaparabrisas y que impidan la visibilidad del conductor o un vehículo de la categoría L5 que contando con parabrisas, micas o similares, tengan objetos impresos, calcomanías, carteles u otros elementos que impidan la visibilidad del conductor. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo que no cuenta con las luces y dispositivos retrorreflectivos previstos en los reglamentos pertinentes.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo sin espejos retrovisores.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo cuando llueve, llovizne o garúe, sin tener operativo el sistema de limpiaparabrisas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo del servicio de transporte público urbano de pasajeros con personas de pie, si la altura interior del vehículo no supera a 1,80 metros.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo con el motor en punto neutro o apagado.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo sin portar el certificado del Seguro Obligatorio de Accidentes de Tránsito o Certificado Contra Accidentes de Tránsito, o que éstos no correspondan al uso del vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo de la categoría M o N con la salida del tubo de escape en la parte lateral derecha, de modo tal que las emisiones o gases sean expulsados hacia la acera por donde circulan los peatones.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo cuya carga o pasajeros obstruya la visibilidad de los espejos laterales.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('En vehículos de las categorías M y N, no llevar puesto el cinturon de seguridad y/o permitir que los ocupantes del vehículo no lo utilicen en los casos en que, de acuerdo a las normas vigentes, exista tal obligación. En vehículos automotores de la categoria L5 no contar con cinturones de seguridad para los asientos de los pasajeros o no tener uno o más soportes fijados a su estructura que permitan a los pasajeros asirse de ellos mientras son transportados.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular en forma desordenada o haciendo maniobras peligrosas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular transportando personas en la parte exterior de la carroceria o permitir que sobresalga parte del cuerpo de la(s) persona(s) transportada(s) en el vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('En las vías públicas urbanas, circular en la noche o cuando la luz natural sea insuficiente o cuando las condiciones de visibilidad sean escasas, sin tener encendido el sistema de luces reglamentarias; o en la red vial nacional y departamental o regional, circular sin tener las luces bajas encendidas durante las veinticuatro (24) horas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular por vías o pistas exclusivas para bicicletas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular transportando cargas que sobrepasen las dimensiones de la carrocería o que se encuentren ubicadas fuera de la misma; o transportar materiales sueltos, fluidos u otros sin adoptar las medidas de seguridad que impidan su caída a la vía.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Remolcar vehículos sin las medidas de seguridad.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Usar luces altas en vías urbanas o hacer mal uso de las luces.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Compartir el asiento de conducir con otra persona, animal o cosa.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No reducir la velocidad al ingresar a un túnel o cruzar un puente, intersecciones o calles congestionadas, cuando transite por cuestas, cuando se aproxime y tome una curva o cambie de dirección, cuando circule por una vía estrecha o sinuosa, cuando se encuentre con un vehículo que circula en sentido contrario o cuando existan peligros especiales con respecto a los peatones u otros vehículos o por razones del clima o condiciones especiales de la vía.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Transitar lentamente por el carril de la izquierda, causando congestión o riesgo o rápidamente por el carril de la derecha.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Aumentar la velocidad cuando es alcanzado por otro vehículo que tiene la intención de sobrepasarlo o adelantarlo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar el vehículo en zonas prohibidas o rigidas señalizadas o sin las señales de seguridad reglamentarias en caso de emergencia. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar o detener el vehículo sobre la línea demarcatoria de intersección, dentro de éstas o en el crucero peatonal (paso peatonal).');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar frente a la entrada o salida de garajes, estacionamientos públicos, vías privadas o en las salidas de salas, espectáculos, centros deportivos en funcionamiento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar a una distancia menor de cinco (5) metros de una bocacalle, de las entradas de hospitales o centros de asistencia médica, cuerpos de bomberos o de hidrantes de servicio contra incendios, salvo los vehículos relacionados a la función del local.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar a menos de tres (3) metros de las puertas de establecimientos educacionales, teatros, iglesias y hoteles, salvo los vehículos relacionados a la función del local.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar a menos de veinte (20) metros de un cruce ferroviario a nivel.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en zonas no permitidas por la autoridad competente, a menos de diez (10) metros de un cruce peatonal o de un paradero de buses, así como en el propio sitio determinado para la parada del bus.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en lugar que afecte la operatividad del servicio de transporte público de pasajeros o carga o que afecte la seguridad, visibilidad o fluidez del tránsito o impida observar la señalización.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un ómnibus, microbus, casa rodante, camión, remolque, semirremolque, plataforma, tanque, tractocamión, tráiler, volquete o furgón, en en vías públicas de zona urbana, excepto en los lugares que habilite para tal fin la autoridad competente, mediante la señalización pertinente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehículo de categorìa M, N u O a una distancia menor a un metro de la parte delantera o posterior de otro ya estacionado, salvo cuando se estacione en diagonal o perpendicular a la vía.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en los terminales o estaciones de ruta, fuera de los estacionamientos externos determinados por la Autoridad competente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehículo automotor por la noche en lugares donde, por la falta de alumbrado público, se impide su visibilidad, o en el día, cuando, por lluvia, llovizna o neblina u otro factor, la visibilidad es escasa, sin mantener encendidas las luces de estacionamiento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehículo en vías con pendientes pronunciadas sin asegurar su inmovilización.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Desplazar o empujar un vehículo bien estacionado, con el propósito de ampliar un espacio o tratar de estacionar otro vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Abandonar el vehículo en la vía pública.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar la vía pública para efectuar reparaciones, salvo casos de emergencia.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Recoger o dejar pasajeros fuera de los paraderos de ruta autorizados, cuando existan.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No respetar las señales que rigen el tránsito, cuyo incumplimiento no se encuentre tipificado en otra infracción. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No presentar la Tarjeta de Identificación Vehicular, la Licencia de Conducir o el Documento Nacional de Identidad o documento de identidad, según corresponda. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo de categoría L, con excepción de la categoría L5, sin tener puesto el casco de seguridad o anteojos protectores, en caso de no tener parabrisas; o permitir que los demás ocupantes no tengan puesto el casco de seguridad. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular con placas ilegibles o sin iluminación o que tengan adherido algún material, que impida su lectura a través de medios electrónicos, computarizados u otro tipo de mecanismos tecnológicos que permitan verificar la comisión de las infracciones de tránsito. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No llevar las placas de rodaje en el lugar que corresponde.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Incumplir con devolver las placas de exhibición, rotativa o transitoria dentro de los plazos establecidos en el Reglamento de Placa Única Nacional de Rodaje. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar señales audibles o visibles iguales o similares a las que utilizan los vehículos de emergencia o vehículos oficiales.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo cuyas características registrables o condiciones técnicas han sido modificadas, alteradas o agregadas, atentando contra la seguridad de los usuarios o por no corresponder los datos consignados en la Tarjeta de Identificación Vehicular con los del vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No ceder el paso a otros vehículos que tienen preferencia.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Seguir a los vehículos de emergencia y vehículos oficiales para avanzar más rápidamente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Detener el vehiculo sobre la demarcación en el pavimento de la señal "No bloquear cruce"');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Dejar mal estacionado el vehículo en lugares permitidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar un vehículo en zonas de parqueo destinadas a vehículos que transportan a personas con discapacidad o conducidos por éstos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar el Permiso Especial de Parqueo para Personas con Discapacidad por parte de una persona a la cual no le corresponde.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Abrir o dejar abierta la puerta de un vehículo estacionado, dificultando la circulación vehicular.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar el carril de giro a la izquierda para continuar la marcha en cualquier dirección que no sea la específicamente señalada.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Arrojar, depositar o abandonar objetos o sustancias en la vía pública que dificulten la circulación.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar la bocina para llamar la atención en forma inncesaria.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Hacer uso de bocinas de descarga de aire comprimido en el ámbito urbano.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir con presencia de alcohol en la sangre en proporción mayor a lo previsto en el Código Penal, o bajo los efectos de estupefacientes, narcóticos y/o alucinógenos comprobado con el exámen respectivo o por negarse al mismo y que haya participado en un accidente de tránsito.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir con presencia de alcohol en la sangre en proporción mayor a lo previsto en el Código Penal, bajo los efectos de estupefacientes, narcóticos y/o alucinógenos comprobada con el exámen respectivo o por negarse al mismo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo automotor sin tener licencia de conducir o permiso provisional.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehículos estando la licencia de conducir retenida, suspendida o estando inhabilitado para obtener licencia de conducir.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo con Licencia de Conducir cuya clase o categoría no corresponde al vehículo que conduce.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar en las curvas, puentes, túneles, zonas estrechas de la vía, pasos a nivel, pasos a desnivel en cambios de rasante, pendientes y cruces de ferrocarril.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Participar en competencias de velocidad en eventos no autorizados.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Permitir a un menor de edad la conducción de un vehículo automotor, sin autorización o permiso provisional.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo con cualquiera de sus sistemas de dirección, frenos, suspensión, luces o eléctrico en mal estado, previa inspección técnica vehicular.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Abastecer de combustible un vehículo del servicio de transporte público de pasajeros con personas a bordo del vehículo.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehículos de las categorías M o N sin parachoques o dispositivo antiempotramiento cuando corresponda; o un vehículo de la categoría L5 sin parachoques posterior, conforme a lo establecido en el Reglamento Nacional de Vehículos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No detenerse al aproximarse a un vehículo de transporte escolar debidamente identificado que está recogiendo o dejando escolares.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No detenerse al llegar a un cruce ferroviario a nivel o reiniciar la marcha sin haber comprobado que no se aproxima tren o vehículo ferroviario, o cruzar la vía ferrea por lugares distintos a los cruces a nivel establecidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular produciendo contaminación en un índice superior a los límites máximos permisibles de emisión de gases contaminantes.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular en sentido contrario al tránsito autorizado.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Cruzar una intersección o girar, estando el semáforo con luz roja y no existiendo la indicación en contrario.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Desobedecer las indicaciones del efectivo de la Policía Nacional del Perú asignado al control del tránsito.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir vehículos sin cumplir con las restricciones que consigna la Licencia de Conducir.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No respetar los límites máximo o mínimo de velocidad establecidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar interrumpiendo totalmente el tránsito.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Detenerse para cargar o descargar mercancías en la calzada y/o en los lugares que puedan constituir un peligro u obstáculo o interrumpan la circulación.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Estacionar o detener el vehículo en el carril de circulación, en carreteras o caminos donde existe berma lateral.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular sin placas de rodaje o sin el permiso correspondiente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('No dar preferencia de paso a los vehíuclos de emergencia y vehículos oficiales cuando hagan uso de sus señales audibles y visibles.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo especial que no se ajuste a las exigencias reglamentarias sin la autorización correspondiente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo que no cuente con el certificado de aprobación de inspección técnica vehicular.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo sin contar con la póliza del Seguro Obligatorio de Accidentes de Tránsito, o Certificado de Accidentes de Tránsito, cuando corresponda, o éstos no se encuentre vigente.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Deteriorar intencionalmente, adulterar, destruir o sustraer las Placas de exhibición, rotativa o transitoria . ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Usar las placas de exhibición, rotativa o transitoria fuera del plazo, horario o ruta establecida o cuando esta ha caducado o ha sido invalidada. ');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Utilizar las placas de exhibición, rotativa o transitoria en vehículos a los que no se encuentren asignadas.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Tramitar u obtener duplicado, recategorización, revalidación, canje o nueva licencia de conducir de cualquier clase, por el infractor cuya licencia de conducir se encuentre retenida, suspendida o cancelada o se encuentre inhabilitado para obtenerla.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Operar maquinaria especial por la vía pública.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Circular produciendo ruidos que superen los límites máximos permisibles.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Voltear en U sobre la misma calzada, en las curvas, puentes, pasos a desnivel, vías expresas, túneles, estructuras elevadas, cima de cuesta, cruce ferroviario a nivel.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Transportar carga sin los dispositivos de sujeción o seguridad establecidos.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir y ocasionar un accidente de tránsito con daños personales inobservando las normas de tránsito dispuestas en el presente Reglamento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir un vehículo para el servicio de transporte público y ocasionar un accidente de tránsito con daños personales inobservando las normas de tránsito dispuestas por el presente Reglamento.');
INSERT INTO TipoDeInfraccion (Nombre) VALUES ('Conducir y ocasionar un accidente de tránsito con lesiones graves o muerte inobservando las normas de tránsito dispuestas en el presente Reglamento.');
